Instead of defining a composite index manually, run your query in your app code to get a link for generating the required index
Error: Error fetching servers: Firestore query requires an index. Please create it in the Firebase console. (Original message: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/serverspotlight-y93vy/firestore/indexes?create_composite=ClVwcm9qZWN0cy9zZXJ2ZXJzcG90bGlnaHQteTkzdnkvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3NlcnZlcnMvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCQoFdm90ZXMQAhoMCghfX25hbWVfXxAC)
    at getFirebaseServers (https://6000-firebase-studio-1746941790571.cluster-fdkw7vjj7bgguspe3fbbc25tra.cloudworkstations.dev/_next/static/chunks/src_3fd13b69._.js:366:15)
    at async HomePage.useCallback[loadData] (https://6000-firebase-studio-1746941790571.cluster-fdkw7vjj7bgguspe3fbbc25tra.cloudworkstations.dev/_next/static/chunks/src_d88f8767._.js:1437:37)